topics:
    - /pcl_gpu_tools/detected_objects
    - /pointcloud_processing_node/detected_objects 
    - /test_topic
    - /detected_objects
    - /pointcloud_lidar_processing/detected_objects

regions:
    #warn
    2: [[3.0, -3.0],
        [3.0, 3.0],
        [-3.0, 3.0],
        [-3.0, -3.0],
        [3.0, -3.0]]
    #danger
    1: [[2.0, -2.0],
        [2.0, 2.0],
        [-2.0, 2.0],
        [-2.0, -2.0],
        [2.0, -2.0]]
    #lethal
    0: [[0.5, 0.50],
        [0.5, -0.50],
        [-0.20, -0.50],
        [-0.20, 0.50],
        [0.5, 0.50]]